version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3000:3000"
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3003:3003"
