export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL';

export const JOIN_ROOM = 'JOIN_ROOM';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const JOIN_ROOM_FAIL = 'JOIN_ROOM_FAIL';

export const RELOAD_ROOM = 'RELOAD_ROOM';
export const RELOAD_ROOM_SUCCESS = 'RELOAD_ROOM_SUCCESS';
export const RELOAD_ROOM_FAIL = 'RELOAD_ROOM_FAIL';

export const REMATCH = 'REMATCH';

export const FETCH_GAME_STATE = 'FETCH_GAME_STATE';

export const USER_INPUT_STEP = 'USER_INPUT_STEP';
